
* Βασίλης Κατσάκος
  :PROPERTIES:
  :DATE:     <2021-03-01 Mon 03:40>
  :END:

https://github.com/billkats/Candy

* Γιάννης Μπαξεβάνης

https://github.com/baxejohn/baxejohn-sonarts-2021

* Αγάπη Ζάρδα

https://github.com/AgapiZa/SONARTS_-2020-21-.git 

* Σοφία Εμμανουηλίδου

https://github.com/Emmionel/flutefinal 

* Βαγγέλης Γιαζιτζής

https://github.com/vangelisgiaz/vangelis-giazi

* Σίσσυ Βαμπίρη

https://github.com/Vampiri/Ergasia_voices

